// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEp1081dy9nVJOKTQGdd8olRuIcyRR0k',
    appId: '1:8619244795:web:44fa13a342723e134a845e',
    messagingSenderId: '8619244795',
    projectId: 'app-gerenciador-de-financas',
    authDomain: 'app-gerenciador-de-financas.firebaseapp.com',
    databaseURL: 'https://app-gerenciador-de-financas-default-rtdb.firebaseio.com',
    storageBucket: 'app-gerenciador-de-financas.firebasestorage.app',
    measurementId: 'G-W3VK0XDFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnY3G4_G-6dO-ADUitPY-zyrmxHf5Ixk',
    appId: '1:8619244795:android:c618fe6c53d3006c4a845e',
    messagingSenderId: '8619244795',
    projectId: 'app-gerenciador-de-financas',
    databaseURL: 'https://app-gerenciador-de-financas-default-rtdb.firebaseio.com',
    storageBucket: 'app-gerenciador-de-financas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3N-DlG33a7fdYMGhg-beVBZVfJtjYio',
    appId: '1:8619244795:ios:2795e9b2c3c602b94a845e',
    messagingSenderId: '8619244795',
    projectId: 'app-gerenciador-de-financas',
    databaseURL: 'https://app-gerenciador-de-financas-default-rtdb.firebaseio.com',
    storageBucket: 'app-gerenciador-de-financas.firebasestorage.app',
    iosBundleId: 'com.example.tcc2025Leanatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkEp1081dy9nVJOKTQGdd8olRuIcyRR0k',
    appId: '1:8619244795:web:1f9ea786786065d64a845e',
    messagingSenderId: '8619244795',
    projectId: 'app-gerenciador-de-financas',
    authDomain: 'app-gerenciador-de-financas.firebaseapp.com',
    databaseURL: 'https://app-gerenciador-de-financas-default-rtdb.firebaseio.com',
    storageBucket: 'app-gerenciador-de-financas.firebasestorage.app',
    measurementId: 'G-3PD9ZPZY2Y',
  );
}
